spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/Employee
spring.datasource.username=postgres
spring.datasource.password=Arunask@12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true